apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: jenkins
spec:
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
  # 关键点：通过修改 version 标签来切换流量 (blue <-> green)
  selector:
    app: demo
    version: green
  type: LoadBalancer
