jenkins_admin_password = "password123"
aliyun_registry_user   = "zhaoqian51@126.com"
aliyun_registry_pass   = "Int3l@123"
github_user            = "jasonsproject"
github_token           = "your_github_token"